[12.0][ADD] helpdesk_mgmt_ticket_start_date
solvosci/slv-helpdesk pull request #11
Opened 2021-02-25 16:47 UTC by ChristianSantamaria

Add an editable Start Date field that initializes with today's date

2021-02-25 17:00 UTC, dalonsod requested changes
Only code review. When comments are attended, I'll test it

2021-02-25 17:00 UTC, dalonsod commented on helpdesk_mgmt_ticket_start_date/README.rst
> +========================
Please update the whole `README.rst` file

2021-02-25 17:00 UTC, dalonsod commented on helpdesk_mgmt_ticket_start_date/__manifest__.py
> +    "version": "12.0.2.1.0",
Wrong version:
```suggestion
    "version": "12.0.1.0.0",
```

2021-02-25 17:00 UTC, dalonsod commented on helpdesk_mgmt_ticket_start_date/views/helpdesk_ticket_views.xml
> +            </xpath>
Could you add making invisible `create_date`?

2021-02-26 09:20 UTC, dalonsod commented
Locally tested, it works :)

Could you add an init hook in order to initialize `start_date` field of existing tickets with their `create_date`?

2021-03-01 11:42 UTC, ChristianSantamaria commented
The init_hook is not running and I don't know why

@dalonsod Could you take a look at it?

2021-03-01 12:12 UTC, dalonsod requested changes

2021-03-01 12:12 UTC, dalonsod commented on helpdesk_mgmt_ticket_start_date/hooks.py
> +        rec.start_date = rec.create_date
When you install, an error is thrown (an "expected singleton" error).
This worked for me (variables were wrong assigned):
```suggestion
    tickets = HelpdeskTicket.search([('start_date', '=', False)])

    for rec in tickets:
        rec.start_date = rec.create_date
```

2021-03-01 15:16 UTC, dalonsod approved these changes
LGTM
@lmiguens-solvos could you review? Thanks!

2021-03-01 17:44 UTC, lmiguens-solvos commented
It works well for me, although I can think of 2 improvements (or questions). 
1.- To be able to modify this date when registering the ticket. Why is it not allowed to modify it? Is it complicated?
and 
2.- Hide the creation date in form view. Perhaps it is no longer necessary having this new start date. It would already be seen only as metadata, as in other entities.

2021-03-01 18:08 UTC, dalonsod commented
> 1.- To be able to modify this date when registering the ticket. Why is it not allowed to modify it? Is it complicated?

It's possible, the current implementation was defined by me.

> 2.- Hide the creation date in form view. Perhaps it is no longer necessary having this new start date. It would already be seen only as metadata, as in other entities.

I agree.

2021-03-02 08:48 UTC, lmiguens-solvos commented
I have already seen that my 2 requests are resolved. Perfect! Thank you!
But now I have a another question @dalonsod 
My new question is about the ticket numbering: if the year was included in the ticket number, should it be created with the year of this new registration date? or will it be too complicated

2021-03-02 09:12 UTC, dalonsod commented
> My new question is about the ticket numbering: if the year was included in the ticket number, should it be created with the year of this new registration date? or will it be too complicated

It seems to be possible, but complicated.

Looking at https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_sequence.py#L103 , it's possible to obtain the proper secuence range depending on a custom date. But I should investigate in depth how to properly call it in this helpdesk context

2021-03-02 09:15 UTC, dalonsod commented on helpdesk_mgmt_ticket_start_date/models/helpdesk_ticket.py
> +    start_date = fields.Datetime()
@ChristianSantamaria  One last suggested change, in order to log modifications:
```suggestion
    start_date = fields.Datetime(track_visibility="onchange")
```

2021-03-02 09:18 UTC, lmiguens-solvos commented
> It seems to be possible, but complicated.

ok, then surely it is not necessary to do so

2021-03-02 09:29 UTC, dalonsod commented
Good!
Please squash commits and, if @lmiguens-solvos agrees, I'll merge it

2021-03-02 10:29 UTC, lmiguens-solvos approved these changes
LGTM

2021-03-02 11:07 UTC, dalonsod commented
Merging...

2021-03-02 11:07 UTC, merged