[12.0][ADD] helpdesk_mgmt_ticket_assignment_massive
solvosci/slv-helpdesk pull request #18
Opened 2021-04-23 10:37 UTC by ChristianSantamaria

Adds an action to assign status and assigned user in bulk.

2021-04-23 11:03 UTC, dalonsod requested changes
See comments

2021-04-23 11:03 UTC, dalonsod commented on helpdesk_mgmt_ticket_assignment_massive/__manifest__.py
> +        Adds an action to assign status and assigned user in bulk.
Suggested:
```suggestion
        Adds an action for tickets to assign status and assigned user in bulk.
```

2021-04-23 11:03 UTC, dalonsod commented on helpdesk_mgmt_ticket_assignment_massive/__manifest__.py
> +        "wizards/assignement_massive.xml",
Typo:
```suggestion
        "wizards/assignment_massive.xml",
```

2021-04-23 11:03 UTC, dalonsod commented on helpdesk_mgmt_ticket_assignment_massive/wizards/assignement_massive.xml
> +</odoo>
Missing EOF line

2021-04-23 11:03 UTC, dalonsod commented on helpdesk_mgmt_ticket_assignment_massive/wizards/assignement_massive.py
> +            if(self.stage_id):
This code doesn't cover to corner cases:
- If `user_id` is not filled, the tickets aren't modified. But, if we want tu unassign those tickets?
- If any ticket has a `team_id` incompatible with the selected `user_id`, an error should be fired and proccss stopped.

2021-04-26 09:01 UTC, ChristianSantamaria commented
> If user_id is not filled, the tickets aren't modified. But, if we want to unassign those tickets?
What would be the best option for this create a checkbox indicating if you want to deallocate the user or create another lower button to deallocate?

2021-04-26 09:02 UTC, dalonsod commented
@ChristianSantamaria I'll test it as soon as possible

2021-04-26 09:04 UTC, dalonsod commented
>What would be the best option for this create a checkbox indicating if you want to deallocate the user or create another lower button to deallocate?

Other options is the selected (leaving empty the field does the trick) and adding a legend in the wizard form explaining that, like ("Please select the new assigned user. If it's empty, the selected tieckets will become unassigned")

2021-04-26 10:55 UTC, dalonsod commented
Locally tested, faced this issues:

- When a user is not valid, the message doesn't show affected ticket number, it should be useful IMO.
- When the user is not filled, testing with three random tickets the following error message was fired: "The assigned user False is not associated with the team Consultants ". When the user is not filled, no checks are needed.
- The ticket list in the wizard form has the label "Ticket" (better "Selected tickets"). Since a custom tree view is not defined, a too long column list is shown. Consider using `widget="many2many_tags"` in this case.

2021-04-27 11:49 UTC, dalonsod commented
@ChristianSantamaria please test the last modifications made. I think only one condition should be tested in this case:
- If user is filled, check if user belongs to current ticket team, if assigned.
- If there's no team for the ticket, every user could be assigned to the ticket.
- Every ticket can be user unassigned.

Tested un a database created from scratch, and only installing this addon.

2021-04-28 12:14 UTC, dalonsod requested changes
Locally tested, LGTM, only the issue describe on other comment

2021-04-28 12:14 UTC, dalonsod commented on helpdesk_mgmt_ticket_assignment_massive/wizards/assignment_massive.py
> +                    ))
Wrong string injection, it actually alters origin string:
```suggestion
                    raise ValidationError(_(
                        'In ticket %s the assigned user %s '
                        'is not associated with team %s'                        
                    ) % (ticket.number, self.user_id.name,
                           ticket.team_id.name)
                    )
```

2021-04-29 06:41 UTC, dalonsod approved these changes
LGTM

@lmiguens-solvos could you review? Thanks!

2021-04-29 11:48 UTC, lmiguens-solvos approved these changes
LGTM

2021-04-29 13:37 UTC, dalonsod commented
Let's merge!

2021-04-29 13:37 UTC, merged