[12.0][ADD] helpdesk_mgmt_timesheet_addline
solvosci/slv-helpdesk pull request #21
Opened 2021-05-04 11:16 UTC by ChristianSantamaria

2021-05-11 09:18 UTC, lmiguens-solvos commented
I tested it and it works.
Although the button is very close to the grid and the translation is missing.
I suppose waiting to see if it is finally done like this or not, right?

2021-05-11 09:25 UTC, ChristianSantamaria commented
Yes, with the design and the translations I'm waiting, since maybe David suggests another way to do it

2021-05-18 06:17 UTC, dalonsod requested changes
Only code review. When required changes attended, I'll test it

2021-05-18 06:17 UTC, dalonsod commented on helpdesk_mgmt_timesheet_addline/__manifest__.py
> +        "hr_timesheet",
Wrong dependency:
```suggestion
        "helpdesk_mgmt_timesheet",
```

2021-05-18 06:17 UTC, dalonsod commented on helpdesk_mgmt_timesheet_addline/__manifest__.py
> +        "views/helpdesk_ticket_timesheet_views.xml",
Please split in two files (one for each affected model)

2021-05-18 14:46 UTC, dalonsod commented
Locally tested, LGTM.

Anyway, updated with these improvements:
- Better definition of button linked action and its form view.
- Styles changed for some of the buttons.
- TODO comment for dummy action method.
- Switched fields on new form view, in order to prevent annoying datepicker for timesheet date.
- Added description to readme and manifest file.

@ChristianSantamaria could you test it, update `README` file and squash commits?

2021-05-18 15:16 UTC, ChristianSantamaria commented
LGTM

2021-05-19 06:46 UTC, dalonsod approved these changes
LGTM

2021-05-19 06:55 UTC, dalonsod commented
@lmiguens-solvos anything else, or is it OK for you? :)

2021-05-19 12:41 UTC, lmiguens-solvos commented
> @lmiguens-solvos anything else, or is it OK for you? :)

When I updated the addon give me this error: 
"psycopg2.IntegrityError: llave duplicada viola restricción de unicidad «act_window_view_unique_mode_per_action»
DETAIL:  Ya existe la llave (act_window_id, view_mode)=(190, form)."
Then I uninstalled it and reinstalled it. And then it works.

I tried the addon and everything was fine, although it would leave the editable attibute at bottom instead of top, since when click the "Add line" I think it is better to open that new line next to where I clicked  "Add line".

On the other hand I verified that the operation of the new button is different from the link "Add line" in the sense that in the window that opens with the new button when clicking "Save" the record is already in the database, although it is discarded later the edition of the ticket, which does not happen with the line that is opened from "Add line"... 
But hey, I do not put problems to that. It is just a comment.

2021-05-20 06:59 UTC, dalonsod commented
> When I updated the addon give me this error:
> "psycopg2.IntegrityError: llave duplicada viola restricción de unicidad «act_window_view_unique_mode_per_action»
> DETAIL: Ya existe la llave (act_window_id, view_mode)=(190, form)."
> Then I uninstalled it and reinstalled it. And then it works.
> 

I think this error should no longer occur, since action and view definition is actually changed in the last commit in order to provent it. Could you update again the addon and check if no error is fired?

> I tried the addon and everything was fine, although it would leave the editable attibute at bottom instead of top, since when click the "Add line" I think it is better to open that new line next to where I clicked "Add line".

Looks coherent. I'll change it.
 
> On the other hand I verified that the operation of the new button is different from the link "Add line" in the sense that in the window that opens with the new button when clicking "Save" the record is already in the database, although it is discarded later the edition of the ticket, which does not happen with the line that is opened from "Add line"...
> But hey, I do not put problems to that. It is just a comment.

Yes, at this time this is the only way we know to achieve the feature, and it's not blocking. I'll add it to `ROADMAP` section.

2021-05-20 09:47 UTC, dalonsod commented
@lmiguens-solvos comments attended

2021-05-24 09:45 UTC, lmiguens-solvos commented
> @lmiguens-solvos comments attended

ok. Seen and ok

2021-05-24 09:45 UTC, lmiguens-solvos approved these changes
LGTM

2021-05-24 10:30 UTC, merged