[ADD] helpdesk_mgmt_ticket_closed_date
solvosci/slv-helpdesk pull request #22
Opened 2021-05-28 09:21 UTC by ChristianSantamaria

2021-06-01 07:54 UTC, dalonsod requested changes
Only code review

2021-06-01 07:54 UTC, dalonsod commented on helpdesk_mgmt_ticket_closed_date/models/helpdesk_ticket.py
> +    closed_date_permits = fields.Boolean(
Better naming suggestion:
```suggestion
    closed_date_editable = fields.Boolean(
```

2021-06-01 07:54 UTC, dalonsod commented on helpdesk_mgmt_ticket_closed_date/models/helpdesk_ticket.py
> +            self.closed_date_permits = True
Code optimization, singleton error prevention, and an slightly different condition (prevent `closed_date` edition whether ticket is not closed, even if user is manager):
```suggestion
        is_manager = self.env.user.has_group('helpdesk_mgmt.group_helpdesk_manager')
        for record in self:
            record.closed_date_permits = record.stage_id.closed and is_manager
```
The proposed condition has one problem: attepting to change `closed_date` when the ticket is not closed (but it's filled due to ticket was closed before). In that case, could you check if standard unsets closed_date, or it remains filled?

2021-06-01 07:54 UTC, dalonsod commented on helpdesk_mgmt_ticket_closed_date/views/helpdesk_ticket_closed_date_view.xml
> +        <field name="inherit_id" ref="helpdesk_mgmt.ticket_view_form"/>
This view removes/replaces two field attributes (`readonly` and `attrs`), so it's a little bit dangeours. In those cases, the best practice is assigning a lower priority. Could you add it?

2021-06-01 14:48 UTC, dalonsod commented
@ChristianSantamaria take a look to the new improvements:
- constrains methods now support multiple records.
- Usage of `filtered` in order to prevent `if`s.
- Improved error message (empty `closed_date` case).
- prepare method for creation date reference (we've got `helpdesk_mgmt_ticket_start_date` addon which adds a new possible reference date).
- Improved `DESCRIPTION` text (pending `README` re-creation)

@lmiguens-solvos could you check?

2021-06-02 09:49 UTC, lmiguens-solvos commented
> @ChristianSantamaria take a look to the new improvements:
> 
> * constrains methods now support multiple records.
> * Usage of `filtered` in order to prevent `if`s.
> * Improved error message (empty `closed_date` case).
> * prepare method for creation date reference (we've got `helpdesk_mgmt_ticket_start_date` addon which adds a new possible reference date).
> * Improved `DESCRIPTION` text (pending `README` re-creation)
> 
> @lmiguens-solvos could you check?

I tested it and it works correctly for me.
I only miss the translation of the closing date validation message.

2021-06-02 11:30 UTC, ChristianSantamaria commented
Latest improvements:
- Creation of the README file
- Creating translations for the error message

2021-06-02 13:04 UTC, dalonsod approved these changes
Let's merge it!

2021-06-02 13:04 UTC, merged

2021-06-02 13:07 UTC, dalonsod commented
@ChristianSantamaria despite this PR is merged, one interesting task should be preparing this addon to be donated to OCA. What do you think?

The adaptation tasks should be the following:
- license and authority in manifest file according to OCA.
- implement tests.
- remove es.po file.
- re-create README.rst file, before changing addon icon.