[15.0][ADD] helpdesk_mgmt_team_customer
solvosci/slv-helpdesk pull request #41
Opened 2024-10-14 15:27 UTC by DantePereyra

Autofills the customer by the team selection.

2024-10-15 07:55 UTC, dalonsod requested changes
See initial comments

2024-10-15 07:55 UTC, dalonsod commented on helpdesk_mgmt_team_customer/__manifest__.py
> +#    Copyright (C) 2020 Solvos Consultoría Informática <www.solvos.es>
Wrong year
```suggestion
#    Copyright (C) 2024 Solvos Consultoría Informática <www.solvos.es>
```

2024-10-15 07:55 UTC, dalonsod commented on helpdesk_mgmt_team_customer/__manifest__.py
> +    "author":  "Solvos, "
Please remove OCA as author

2024-10-15 07:55 UTC, dalonsod commented on helpdesk_mgmt_team_customer/i18n/es_ES.po
> +# Translation of Odoo Server.
Proper file name for general spanish is actually `es.po`.

2024-10-15 07:55 UTC, dalonsod commented on helpdesk_mgmt_team_customer/models/helpdesk_ticket.py
> +from odoo import models, api
For every `.py` file (but `__init__.py`) add copyright comment lines

2024-10-15 07:55 UTC, dalonsod commented on helpdesk_mgmt_team_customer/models/res_partner.py
> +from odoo import models, fields
Remove this file, as unused.

2024-10-15 08:07 UTC, DantePereyra commented
Changes done.

2024-10-15 10:36 UTC, dalonsod requested changes
See new comments

2024-10-15 10:36 UTC, dalonsod commented on helpdesk_mgmt_team_customer/__manifest__.py
> +    "website": "https://github.com/OCA/helpdesk",
Wrong website:
```suggestion
    "website": "https://github.com/solvosci/slv-helpdesk",
```

2024-10-15 10:36 UTC, dalonsod commented on helpdesk_mgmt_team_customer/models/__init__.py
> +from . import res_partner
If this import is not removed, an error will raise

2024-10-15 11:37 UTC, DantePereyra commented
Changes done and added README.rst

2024-10-15 16:43 UTC, dalonsod commented
OK, I'll test it ASAP

2024-10-16 09:58 UTC, dalonsod approved these changes
Tested :+1: 

Only minor change should be made: icon.png file is placed in a wrong folder (it should be located inside `static/description` folder, not `static` one). Once done, I'll merge it

2024-10-16 10:12 UTC, DantePereyra commented
Icon changed to `static/description`

2024-10-16 10:15 UTC, merged

2024-10-16 10:15 UTC, dalonsod commented
Congrats @DantePereyra your first merged PR!!